import React from 'react'
import { Container } from 'react-bootstrap'
import Head from 'next/head'
import styles from './Layout.module.css'
export default function Layout({children}) {
    return (
        <Container className={styles.container}>
            <Head>
                <title>The Today Weather</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                {children}
            </main>
        </Container>
    )
}
